[package]
name = "linear_regression"
version = "0.1.0"
authors = ["Krystalz42 <aroulin@stundent.42.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1"
flot = "0.1.3"
json = "0.11.15"